name: Deploy to ECS
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      APP_ENV: production
      CUSTOM_OPENAI_KEY: ${{ secrets.CUSTOM_OPENAI_KEY }}
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASS: ${{ secrets.DB_PASS }}
      DB_NAME: ${{ secrets.DB_NAME }}
      AWS_ECR_REPO: ${{ secrets.AWS_ECR_REPO }}
      ECS_EXECUTION_ROLE_ARN: ${{ secrets.ECS_EXECUTION_ROLE_ARN }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1
      
      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password --region ap-northeast-1 | docker login --username AWS --password-stdin ${{ secrets.AWS_ECR_REPO }}
      
      - name: Build and push Docker image
        run: |
          docker build --no-cache -t emotion_analysis .
          docker tag emotion_analysis:latest ${{ secrets.AWS_ECR_REPO }}:latest
          docker push ${{ secrets.AWS_ECR_REPO }}:latest
      
      - name: Get current service definition
        run: |
          # 現在のサービス定義を取得して、コンテナ名を確認
          aws ecs describe-services \
            --cluster emotion_analysis-cluster \
            --services emotion_analysis-service \
            --query "services[0].deployments[0].taskDefinition" --output text > current_task_def_arn.txt
          
          CURRENT_TASK_DEF=$(cat current_task_def_arn.txt)
          echo "現在のタスク定義: $CURRENT_TASK_DEF"
          
          # コンテナ名を取得
          CONTAINER_NAME=$(aws ecs describe-task-definition \
            --task-definition $CURRENT_TASK_DEF \
            --query "taskDefinition.containerDefinitions[0].name" --output text)
          
          echo "使用するコンテナ名: $CONTAINER_NAME"
          echo "CONTAINER_NAME=$CONTAINER_NAME" >> $GITHUB_ENV
      
      - name: Create task definition with direct values
        run: |
          # 環境変数をJSONエスケープ
          ESCAPED_OPENAI_KEY=$(echo "$CUSTOM_OPENAI_KEY" | sed 's/"/\\"/g')
          export ESCAPED_OPENAI_KEY
          
          cat << EOF > task-def.json
          {
            "family": "emotion_analysis-task",
            "networkMode": "awsvpc",
            "requiresCompatibilities": ["FARGATE"],
            "cpu": "256",
            "memory": "512",
            "executionRoleArn": "${ECS_EXECUTION_ROLE_ARN}",
            "containerDefinitions": [
              {
                "name": "${CONTAINER_NAME}",
                "image": "${AWS_ECR_REPO}:latest",
                "essential": true,
                "portMappings": [
                  {
                    "containerPort": 3000,
                    "protocol": "tcp"
                  }
                ],
                "environment": [
                  { "name": "APP_ENV", "value": "production" },
                  { "name": "DB_HOST", "value": "${DB_HOST}" },
                  { "name": "DB_USER", "value": "${DB_USER}" },
                  { "name": "DB_PASS", "value": "${DB_PASS}" },
                  { "name": "DB_NAME", "value": "${DB_NAME}" },
                  { "name": "CUSTOM_OPENAI_KEY", "value": "${ESCAPED_OPENAI_KEY}" },
                  { "name": "CUSTOM_OPENAI_KEY", "value": "${CUSTOM_OPENAI_KEY}" }
                ],
                "logConfiguration": {
                  "logDriver": "awslogs",
                  "options": {
                    "awslogs-group": "/ecs/emotion_analysis",
                    "awslogs-region": "ap-northeast-1",
                    "awslogs-stream-prefix": "ecs"
                  }
                }
              }
            ]
          }
          EOF
          
          echo "===== タスク定義ファイル内容確認 ====="
          cat task-def.json
      
      - name: Register new ECS task definition
        run: |
          aws ecs register-task-definition --cli-input-json file://task-def.json
      
      - name: Deploy to ECS
        run: |
          # 最新のタスク定義を取得
          TASK_DEF=$(aws ecs describe-task-definition --task-definition emotion_analysis-task --query 'taskDefinition.taskDefinitionArn' --output text)
          
          # サービスの更新（強制デプロイ）
          aws ecs update-service \
            --cluster emotion_analysis-cluster \
            --service emotion_analysis-service \
            --task-definition $TASK_DEF \
            --force-new-deployment
      
      - name: Verify deployed task definition
        run: |
          echo "現在アクティブなタスク定義:"
          aws ecs describe-services \
            --cluster emotion_analysis-cluster \
            --services emotion_analysis-service \
            --query "services[0].taskDefinition"
          
          echo "アクティブタスクの環境変数:"
          ACTIVE_TASK=$(aws ecs describe-services \
            --cluster emotion_analysis-cluster \
            --services emotion_analysis-service \
            --query "services[0].taskDefinition" --output text)
          
          aws ecs describe-task-definition \
            --task-definition $ACTIVE_TASK \
            --query "taskDefinition.containerDefinitions[0].environment"